version: '3.7'
volumes:
  redisdata:
  mongodata:

services:
  redis:
    restart: on-failure
    image: redis:6.0.1
    volumes:
      - redisdata:/data

  mongo:
    restart: on-failure
    image: mongo:4.4-bionic
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=sample

  backend:
    restart: on-failure
    build: ./
    volumes:
      - ./:/app
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=info
      - MONGO_DB=sample
      - EXPRESS_PORT=3000
    ports:
      - "3000:3000"